### ISSUE TITLE
Watch for dependencies

### ISSUE THREAD

**Issue by lzrski** [ulisses-alves/rollup-plugin-elm#2]
It would be great to make Rollup watch for Elm dependencies. Once https://github.com/rollup/rollup/pull/2259 lands it shouldn't be very difficult using `findAllDependencies` from rtfeldman/node-elm-compiler.

I may give it a shot as Elm + CoffeeScript 2 + Rollup is becoming my new favorite setup. Let's hope the Rollup PR is merged soon 😄

**Comment by lzrski** [comment]
Oh, wait! It's already merged. I'm a dummy :D

**Comment by ulisses-alves** [comment]
Cool! Here it is:

546a806c0481948d343a5bad776be848634882de

**Comment by lzrski** [comment]
Wow, man! You are the best. I'll check it out today evening.

**Comment by lzrski** [comment]
Works as advertised 🎉 Thank you.
